# - Build vue app
# - Zip built app
# - Upload zip
# - On remote:
#   - Delete all files
#   - Unzip zip

name: Deploy to Server

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      
      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Build app
        run: yarn build

      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./dist
    
  upload_files:
    name: Upload files to remote server
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: dist
          path: ./dist
      
      - name: Upload Files to Remote
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          local-dir: "./dist/"
          server-dir: "/public_html/tmp/"
          dry-run: false
  
  remove_files:
    name: Remove unused files from remote server
    needs: upload_files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/public_html;
            find ~/public_html -mindepth 1 -not \( -name "tmp" -o -name ".well-known" \) -delete;
            mv ~/public_html/tmp/* ~/public_html;
